apiVersion: v1
kind: Secret
metadata:
  name: workercontagemsecret
type: Opaque
data:
  ConnectionSqlServer: <STRING DE CONEXÃO DO SQL SERVER EM BASE 64>
  ConnectionRabbitMQ: <STRING DE CONEXÃO DO RABBITMQ EM BASE 64>
  ConnectionAppInsights: <STRING DE CONEXÃO DO APPLICATION INSIGHTS EM BASE 64>